// Generated by CoffeeScript 1.9.3

/*
  jsw.coffee
  A translator for an alternate Javascript syntax that uses significant whitespace
 */

(function() {
  var Uglify, args, ast, file, fs, i, jsCode, jswCode, jswCodeStream, jswMappings, len, log, meta, metaStr, opts, ref, utils;

  log = require('debug')('jsw');

  fs = require('fs');

  utils = require('./utils');

  args = require('./args');

  Uglify = require("uglify-js2");

  meta = require('./meta');

  ref = args.files;
  for (i = 0, len = ref.length; i < len; i++) {
    file = ref[i];
    console.log("\nvvvvvvvvvvvvvvvvvv");
    jsCode = fs.readFileSync(file, 'utf8');
    if (args.tojsw) {
      ast = Uglify.parse(jsCode);
      utils.dumpAst(ast);
      fs.writeFileSync('test/ast.json', JSON.stringify(ast));
      opts = {
        beautify: true,
        indent_level: 2
      };
      if (args.map) {
        jswMappings = [];
        opts.node_map = {
          add: function(node_gen_map) {
            return jswMappings.push(node_gen_map);
          }
        };
      }
      jswCodeStream = Uglify.OutputStream(opts);
      ast.print(jswCodeStream);
      jswCode = jswCodeStream.toString();
      metaStr = (args.map ? meta.encode(jsCode, jswCode, jswMappings) : '');
      fs.writeFileSync('test/jswCode.jsw', jswCode + metaStr);
    }
    console.log("^^^^^^^^^^^^^^^^^^\n");
  }

}).call(this);
