// Generated by CoffeeScript 1.9.3

/*
  jsw.coffee
  A translator for an alternate Javascript syntax that uses significant whitespace
 */

(function() {
  var acorn, args, codegen, comments, file, fs, genJSW, generated, i, jsIn, jsInAst, jsOut, len, log, pfx, ref, tokens, util, whitespace, whitespaces;

  log = require('debug')('jsw');

  fs = require('fs');

  util = require('util');

  acorn = require('acorn');

  codegen = require('escodegen');

  args = require('./args');

  genJSW = require('./genJSW');

  whitespace = require('./whitespace');

  ref = args.files;
  for (i = 0, len = ref.length; i < len; i++) {
    file = ref[i];
    pfx = 'test/';
    jsIn = fs.readFileSync(file, 'utf8');
    comments = tokens = whitespaces = null;
    if (args.parse) {
      comments = [];
      tokens = [];
      jsInAst = acorn.parse(jsIn, {
        ecmaVersion: 6,
        sourceType: 'script',
        allowHashBang: true,
        preserveParens: false,
        ranges: true,
        onComment: comments,
        onToken: tokens
      });
      codegen.attachComments(jsInAst, comments, tokens);
      fs.writeFileSync(pfx + 'in-ast.json', JSON.stringify(jsInAst));
      generated = genJSW.generate(jsInAst, {
        comment: true,
        sourceMap: true,
        sourceMapWithCode: true
      });
      fs.writeFileSync(pfx + 'final.jsw', generated.code);
    } else {
      log('not parse');
      jsInAst = JSON.parse(fs.readFileSync(pfx + 'in-ast.json', 'utf8'));
    }
    if (args.comments && comments) {
      fs.writeFileSync(pfx + 'comments', util.inspect(comments, {
        depth: null
      }));
    }
    if (args.tokens && tokens) {
      fs.writeFileSync(pfx + 'tokens', util.inspect(tokens, {
        depth: null
      }));
    }
    if (args.comments && comments && args.tokens && tokens) {
      whitespaces = whitespace.get(jsIn, tokens, comments);
      fs.writeFileSync(pfx + 'whitespaces', util.inspect(whitespaces, {
        depth: null
      }));
    }
    if (args.gen) {
      jsOut = codegen.generate(jsInAst, {
        comment: true
      });
      fs.writeFileSync(pfx + 'out.js', jsOut);
    }
  }

}).call(this);
