// Generated by CoffeeScript 1.9.3

/*
  jsw.coffee
  A translator for an alternate Javascript syntax that uses significant whitespace
 */

(function() {
  var acorn, args, ast, codegen, comments, file, fs, genJSW, generated, i, jsIn, len, log, pfx, ref, tokens, util, whitespace, whitespaces;

  log = require('debug')('jsw');

  fs = require('fs');

  util = require('util');

  acorn = require('acorn');

  codegen = require('escodegen');

  args = require('./args');

  genJSW = require('./genJSW');

  whitespace = require('./whitespace');

  ref = args.files;
  for (i = 0, len = ref.length; i < len; i++) {
    file = ref[i];
    pfx = 'test/';
    jsIn = fs.readFileSync(file, 'utf8');
    comments = tokens = whitespaces = null;
    if (args.parse) {
      comments = [];
      tokens = [];
      ast = acorn.parse(jsIn, {
        ecmaVersion: 6,
        sourceType: 'script',
        allowHashBang: true,
        preserveParens: false,
        ranges: true,
        onComment: comments,
        onToken: tokens
      });
      codegen.attachComments(ast, comments, tokens);
      fs.writeFileSync(file + '-ast.json', JSON.stringify(ast));
      generated = genJSW.generate(ast, {
        comment: true,
        file: jsIn
      });
      fs.writeFileSync('test/jsw-ast.json', JSON.stringify(ast));
      fs.writeFileSync(pfx + 'final.jsw', generated.code);
    }
  }

}).call(this);
