// Generated by CoffeeScript 1.9.3
(function() {
  var Uglify, fs, log;

  log = require('debug')('utils');

  fs = require('fs');

  Uglify = require("uglify-js2-tojsw");

  exports.dumpAst = function(ast, file) {
    var tt;
    tt = new Uglify.TreeTransformer(null, function(node) {
      node.startPos = node.start.pos;
      node.endPos = node.end.pos;
      delete node.start;
      delete node.end;
      node.type = node.TYPE;
      if ((node.body == null) || node.body.length === 0) {
        delete node.body;
      }
      return node;
    });
    fs.writeFileSync(file + '-ast-dump.json', JSON.stringify(ast.transform(tt)));
    return ast;
  };

}).call(this);
