// Generated by CoffeeScript 1.9.3
(function() {
  exports.get = function(code, tokens, comments) {
    var comment, end, i, j, k, len, len1, len2, pos, range, start, token, tokenAndCommentRanges, whitespace;
    tokenAndCommentRanges = [];
    for (i = 0, len = tokens.length; i < len; i++) {
      token = tokens[i];
      tokenAndCommentRanges.push(token.range);
    }
    for (j = 0, len1 = comments.length; j < len1; j++) {
      comment = comments[j];
      tokenAndCommentRanges.push(comment.range);
    }
    tokenAndCommentRanges.sort();
    whitespace = [];
    pos = 0;
    for (k = 0, len2 = tokenAndCommentRanges.length; k < len2; k++) {
      range = tokenAndCommentRanges[k];
      start = range[0];
      end = range[1];
      if (start > pos) {
        whitespace.push({
          value: code.slice(pos, start),
          range: [pos, start]
        });
      }
      pos = end;
    }
    return whitespace;
  };

}).call(this);
